<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
    <PackageReference Include="Scriban" Version="6.5.2" />
    <PackageReference Include="StudCoreKit.Framework" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\TgBotProjects\StudTgBotApi\StudTgBotApi.Contracts\StudTgBotApi.Contracts.csproj" />
    <ProjectReference Include="..\..\..\_Shared_\DigiStore.Enums\DigiStore.Enums.csproj" />
    <ProjectReference Include="..\DigiStore.TgBot.Contracts\DigiStore.TgBot.Contracts.csproj" />
    <ProjectReference Include="..\DigiStore.TgBot.Domain\DigiStore.TgBot.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Buttons.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\Catalog\" />
  </ItemGroup>

</Project>
