<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DigiStore.Core" Version="0.0.6" />
    <PackageReference Include="DigiStore.Framework" Version="0.0.7" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigiStore.UserService.Contracts\DigiStore.UserService.Contracts.csproj" />
    <ProjectReference Include="..\DigiStore.UserService.Domain\DigiStore.UserService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
