@DigiStore.TgBot.Web_HostAddress = http://localhost:5237

GET {{DigiStore.TgBot.Web_HostAddress}}/todos/
Accept: application/json

###

GET {{DigiStore.TgBot.Web_HostAddress}}/todos/1
Accept: application/json

###
