<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>

    <!-- Включаем reflection для разработки -->
    <JsonSerializerIsReflectionEnabledByDefault Condition="'$(Configuration)' == 'Debug'">true</JsonSerializerIsReflectionEnabledByDefault>
    <!-- Для Release используем source generators -->
    <PublishTrimmed Condition="'$(Configuration)' == 'Release'">true</PublishTrimmed>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigiStore.TgBot.Application\DigiStore.TgBot.Application.csproj" />
    <ProjectReference Include="..\DigiStore.TgBot.Infrastructure\DigiStore.TgBot.Infrastructure.csproj" />
  </ItemGroup>
  
</Project>
