<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StudCoreKit.Core" Version="0.1.0" />
    <PackageReference Include="StudCoreKit.Framework" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\_WebClients_\TgBot\DigiStore.TgBot.Contracts\DigiStore.TgBot.Contracts.csproj" />
    <ProjectReference Include="..\DigiStore.WalletService.Contracts\DigiStore.WalletService.Contracts.csproj" />
    <ProjectReference Include="..\DigiStore.WalletService.Domain\DigiStore.WalletService.Domain.csproj" />
  </ItemGroup>

</Project>
