// <auto-generated />
using System;
using System.Collections.Generic;
using DigiStore.TgBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigiStore.TgBot.Infrastructure.Migrations
{
    [DbContext(typeof(TgBotDbContext))]
    [Migration("20260112231143_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TgBot")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigiStore.TgBot.Domain.CommandHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId");

                    b.ToTable("command_histories", "TgBot");
                });

            modelBuilder.Entity("DigiStore.TgBot.Domain.Localization", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("En")
                        .HasColumnType("text");

                    b.Property<string>("Ru")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Key");

                    b.ToTable("localizations", "TgBot");
                });

            modelBuilder.Entity("DigiStore.TgBot.Domain.TgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users", "TgBot");
                });

            modelBuilder.Entity("DigiStore.TgBot.Domain.TgUserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("LastActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CachedProfile", "DigiStore.TgBot.Domain.TgUserSession.CachedProfile#CachedUserProfileVO", b1 =>
                        {
                            b1.Property<decimal>("Balance")
                                .HasPrecision(18, 2);

                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<bool>("IsActive");

                            b1.Property<string>("LangCode")
                                .IsRequired()
                                .HasMaxLength(10);

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.PrimitiveCollection<string>("Roles")
                                .IsRequired();

                            b1.Property<long>("TelegramId");

                            b1.Property<DateTime>("UpdatedAt");

                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Username")
                                .HasMaxLength(50);

                            b1.ToJson("CachedProfile");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TelegramId");

                    b.ToTable("sessions", "TgBot");
                });
#pragma warning restore 612, 618
        }
    }
}
