<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    
    <!-- Только в Release версии -->
    <PublishAot Condition="'$(Configuration)' == 'Release'">true</PublishAot>

    <!-- Включаем reflection для разработки -->
    <JsonSerializerIsReflectionEnabledByDefault Condition="'$(Configuration)' == 'Debug'">true</JsonSerializerIsReflectionEnabledByDefault>
    <!-- Для Release используем source generators -->
    <PublishTrimmed Condition="'$(Configuration)' == 'Release'">true</PublishTrimmed>
    <UserSecretsId>eb2bf6f8-4e03-4b2e-b6fd-c609270a0690</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\_WebClients_\TgBot\DigiStore.TgBot.Contracts\DigiStore.TgBot.Contracts.csproj" />
    <ProjectReference Include="..\DigiStore.WalletService.Application\DigiStore.WalletService.Application.csproj" />
    <ProjectReference Include="..\DigiStore.WalletService.Contracts\DigiStore.WalletService.Contracts.csproj" />
    <ProjectReference Include="..\DigiStore.WalletService.Infrastructure.Postgres\DigiStore.WalletService.Infrastructure.Postgres.csproj" />
    <ProjectReference Include="..\DigiStore.WalletService.Infrastructure.Yookassa\DigiStore.WalletService.Infrastructure.Yookassa.csproj" />
  </ItemGroup>
  
</Project>
